### ISSUE TITLE
Generating new pictures asynchronously

### ISSUE THREAD

**Issue by contrun** [io12/org-fragtog#2]
Hi, thank you for your efforts. I find this really helpful.

My only complaint is that when I move the point out of latex fragments, emacs blocks. It takes about 2 seconds for me to generate a new picture, and I am not able to do anything. My emacs-fu is not so good as to contribute this package. Can you give me some technical details on this issue? Is it possible to generate new pictures in the background and display it when it is ready without blocking my editing?

**Comment by io12** [comment]
I'm glad you find my package helpful!

The blocking is because rendering org fragments takes time. If you render fragments without org-fragtog, it also blocks. The previews are cached by default in `ltximg/`, which helps a bit, but new renders are still slow.

Unfortunately, I don't think async org latex fragments are currently possible, but I can look into other packages for async latex rendering like [texfrag](https://github.com/TobiasZawada/texfrag).

**Comment by fbob** [comment]
Thanks for your great package ! :)
Is it possible to combine both: texfrag + org-fragtog ?

**Comment by io12** [comment]
I don't think that's possible, since org-fragtog relies on org-mode's built-in inline latex fragments and (as far as I know) texfrag replaces this with AUCTeX previews.
