### ISSUE TITLE
Problem about determination of latex-fragment

### ISSUE THREAD

**Issue by wugouzi** [io12/org-fragtog#3]
Thanks for your packages. I find that when typing space before $, it will determine wrongly and begin to generate picture.
For example, when the context is $x\in$ and then type a space $x\in $. Or with $x\in X$ and then delete 'X" $x\in $

**Comment by io12** [comment]
Good catch. I will look into this.

**Comment by io12** [comment]
It turns out that org-mode doesn't recognize `$x\in $` as a LaTeX fragment. If you render it to a PDF it won't render properly. If you use the syntax `\(x\in \)` it works. According to the org-mode documentation, this is to prevent conflicts when writing currency amounts (e.g. `I have $100`). https://orgmode.org/manual/LaTeX-fragments.html
